
spring.datasource.url=jdbc:postgresql://postgres:5432/inventory_db
spring.datasource.username=postgres
spring.datasource.password=0208

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true